// Generated by tools/build_e1m2.py. Edit that, not this.
export var E1M2 = {
 "name": "E1M2: THE FURNACE",
 "floor": "slab",
 "ceil": "ceilDark",
 "par": 300,
 "playerAngle": -1.5707963,
 "ceilHeight": 2.5,
 "map": [
  "####################################",
  "########HHHHHHHHHXHHHHHHHHHH########",
  "########H..................H########",
  "########H.h..t........t..+.H########",
  "########H.....~~~~~~~~.....H########",
  "########H..................H########",
  "########H........b.........H########",
  "%%%=%%%%H.....H......H.....HMMMMMMMM",
  "%......%H.....H......H.....HM.....MM",
  "%.i....%H.......a..a.......HM...iAMM",
  "%......%H..................HM..r..MM",
  "%......%HHHHHHHHHRHHHHHHHHHHM.....MM",
  "%..i...%t.......t.t........tM......M",
  "%......D.a................o.M....M.M",
  "%..%%..%......~~~~~~~~......D....M.M",
  "%......%...T..~~~~~~~~..T...M.MM.M.M",
  "%......%......~~~HH~~~......M....M.M",
  "%......%..i...~~~HH~~~...i..M....M.M",
  "%......%......~~~~~~~~......M...g..M",
  "%.%%...%......~~~~~~~~......M......M",
  "%......%...T............T...M.MM...M",
  "%....i.D..h.................D......M",
  "%......%t.................btM......M",
  "%...h..%.o..t..........t....M.g..+.M",
  "%......%####............####M......M",
  "%%S%%%%%####.......b....####MMMMMMMM",
  "#...########.....p......############",
  "#*Pa########............############",
  "####################################",
  "####################################"
 ],
 "heights": [
  "000000000000000000000000000000000000",
  "000000000000000000000000000000000000",
  "000000000666222228222222666000000000",
  "000000000666222222222222666000000000",
  "000000000666220000000022666000000000",
  "000000000666222222222222666000000000",
  "000000000666422222222224666000000000",
  "000000000666222222222222666000000000",
  "033333300666222222222222666008888810",
  "033333300666222222222222666008888810",
  "033333300666222222222222666008888810",
  "011111100000000000000000000008888810",
  "011111102222222222222222222208888880",
  "011111102222222222222222222201111170",
  "011111102222220000000022222201111160",
  "011111102222220000000022222201111150",
  "011111102222220000000022222201111140",
  "011111102222220000000022222201111130",
  "011111102222220000000022222201111120",
  "011111102222220000000022222201111110",
  "011111102222222222222222222201111110",
  "011111102222222222222222222201111110",
  "011111102222222222222222222201111110",
  "011111102222332222222233222201111110",
  "011111100000448888888844000001111110",
  "000000000000558888888855000000000000",
  "011100000000668888888866000000000000",
  "011100000000778888888877000000000000",
  "000000000000000000000000000000000000",
  "000000000000000000000000000000000000"
 ],
 "ceilings": [
  "....................................",
  "....................................",
  ".........qqqqqqqqqqqqqqqqqq.........",
  ".........qqqqqqqqqqqqqqqqqq.........",
  ".........qqqqqqqqqqqqqqqqqq.........",
  ".........qqqqqqqqqqqqqqqqqq.........",
  ".........qqqqqqqqqqqqqqqqqq.........",
  ".........qqqqqqqqqqqqqqqqqq.........",
  ".eeeeee..qqqqqqqqqqqqqqqqqq..kkkkkk.",
  ".eeeeee..qqqqqqqqqqqqqqqqqq..kkkkkk.",
  ".eeeeee..qqqqqqqqqqqqqqqqqq..kkkkkk.",
  ".eeeeee......................kkkkkk.",
  ".eeeeee.mmmmmmmmmmmmmmmmmmmm.kkkkkk.",
  ".eeeeee.mmmmmmmmmmmmmmmmmmmm.kkkkkk.",
  ".eeeeee.mmmmmmmmmmmmmmmmmmmm.kkkkkk.",
  ".eeeeee.mmmmmmmmmmmmmmmmmmmm.kkkkkk.",
  ".eeeeee.mmmmmmmmmmmmmmmmmmmm.kkkkkk.",
  ".eeeeee.mmmmmmmmmmmmmmmmmmmm.kkkkkk.",
  ".eeeeee.mmmmmmmmmmmmmmmmmmmm.kkkkkk.",
  ".eeeeee.mmmmmmmmmmmmmmmmmmmm.kkkkkk.",
  ".eeeeee.mmmmmmmmmmmmmmmmmmmm.kkkkkk.",
  ".eeeeee.mmmmmmmmmmmmmmmmmmmm.kkkkkk.",
  ".eeeeee.mmmmmmmmmmmmmmmmmmmm.kkkkkk.",
  ".eeeeee.mmmmmmmmmmmmmmmmmmmm.kkkkkk.",
  ".eeeeee.....mmmmmmmmmmmm.....kkkkkk.",
  "............mmmmmmmmmmmm............",
  ".eee........mmmmmmmmmmmm............",
  ".eee........mmmmmmmmmmmm............",
  "....................................",
  "...................................."
 ],
 "events": [
  {
   "when": {
    "use": [
     3,
     7
    ]
   },
   "do": [
    {
     "notice": "THE FURNACE IS DRAINING!"
    },
    {
     "shake": 3
    },
    {
     "say": "YOU DID IT! THE PIT'S DRAINING. THAT'S A SHORTCUT STRAIGHT TO THE RED DOOR."
    },
    {
     "lava": [
      14,
      14,
      21,
      19
     ],
     "on": false
    },
    {
     "raise": [
      14,
      14,
      21,
      19
     ],
     "to": 0.5,
     "speed": 0.25
    }
   ]
  },
  {
   "when": {
    "enter": [
     12,
     5,
     23,
     9
    ]
   },
   "do": [
    {
     "seal": [
      "17,11"
     ]
    },
    {
     "notice": "SEALED IN!"
    },
    {
     "shake": 2
    },
    {
     "say": "IT'S A TRAP! KEEP MOVING, USE THE PILLARS AND THE HIGH GROUND."
    },
    {
     "after": 2.0,
     "do": [
      {
       "wave": "forge1",
       "spawn": [
        {
         "kind": "imp",
         "x": 10,
         "z": 3
        },
        {
         "kind": "imp",
         "x": 25,
         "z": 3
        },
        {
         "kind": "gnasher",
         "x": 17,
         "z": 3
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "when": {
    "cleared": "forge1"
   },
   "do": [
    {
     "say": "ONE MORE WAVE. THEY ALWAYS SEND ONE MORE."
    },
    {
     "after": 1.5,
     "do": [
      {
       "wave": "forge2",
       "spawn": [
        {
         "kind": "gnasher",
         "x": 10,
         "z": 9
        },
        {
         "kind": "gnasher",
         "x": 25,
         "z": 9
        },
        {
         "kind": "imp",
         "x": 10,
         "z": 5
        },
        {
         "kind": "imp",
         "x": 25,
         "z": 5
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "when": {
    "cleared": "forge2"
   },
   "do": [
    {
     "notice": "FORGE CLEARED!"
    },
    {
     "open": [
      "17,11"
     ]
    },
    {
     "say": "THAT WAS AWESOME. THE EXIT SWITCH IS BEHIND THE PLINTH. IT'S SINKING NOW."
    },
    {
     "lower": [
      17,
      2,
      17,
      2
     ],
     "to": 0.5,
     "speed": 0.6
    }
   ]
  }
 ],
 "triggers": [
  {
   "box": [
    14,
    24,
    21,
    27
   ],
   "say": "WELCOME TO THE FURNACE! SEE THE LAVA PIT? A SWITCH SOMEWHERE DRAINS IT. THE RED DOOR BEHIND IT LEADS OUT."
  },
  {
   "box": [
    1,
    11,
    6,
    24
   ],
   "say": "DARK IN HERE. LISTEN FOR THE IMPS BEFORE YOU SEE THEM."
  },
  {
   "box": [
    29,
    12,
    34,
    24
   ],
   "say": "THE RED KEYCARD IS UP ON THE TANKS. THE STAIRS ARE ON THE FAR WALL."
  }
 ],
 "lights": [
  {
   "id": "pit",
   "x": 17.5,
   "z": 17,
   "y": 1.2,
   "color": 16738842,
   "intensity": 5,
   "dist": 14
  },
  {
   "id": "forge",
   "x": 17.5,
   "z": 5,
   "y": 3,
   "color": 16730640,
   "intensity": 4,
   "dist": 14
  },
  {
   "id": "tanks",
   "x": 31.5,
   "z": 16,
   "y": 3.5,
   "color": 6990079,
   "intensity": 2.5,
   "dist": 12
  },
  {
   "id": "bunkerflicker",
   "x": 3.5,
   "z": 16,
   "y": 2.5,
   "color": 16760960,
   "intensity": 1.6,
   "dist": 8,
   "flicker": true
  }
 ],
 "darkZones": [
  [
   1,
   8,
   6,
   27
  ]
 ]
};
