// Generated by tools/build_e1m3.py. Edit that, not this.
export var E1M3 = {
 "name": "E1M3: THE RESET ENGINE",
 "floor": "slab",
 "ceil": "ceilDark",
 "par": 330,
 "playerAngle": -1.5707963,
 "ceilHeight": 2.5,
 "map": [
  "#####HHHHHHHHHHHHXHHHHHHHHHHHHH#####",
  "#####H........................H#####",
  "#####H.+..t..............t....H#####",
  "#####H.....H...HHHHHH...H.....H#####",
  "#####H.........HHHHHH.........H#####",
  "#####H......b..HHHHHH.........H#####",
  "#####H........................H#####",
  "#####H.......~........~.......H#####",
  "#####H.....H.~...HH...~.H.....H#####",
  "#####H.......~........~.....a.H#####",
  "#####H........................H#####",
  "#####HHHHHHHHHHHHDDHHHHHHHHHHHH#####",
  "################H..H################",
  "################H..H################",
  "################H..H################",
  "%%=%%%###=######H..H##########HHH=HH",
  "%....%#...ia.###H..H##########H....H",
  "%i...%H......LHHH..HHHHHHHHHHHHi..AH",
  "%....%..........t..t..........H..g.H",
  "%.i%.%.h......................H....H",
  "%..%.%......Mi.........M..o...H~..~H",
  "%M.%.%...M.....~~~~~~.....M...H~..~H",
  "%..%.%.........~HHHH~.........H~..~H",
  "%..%.%tM.......~HHHH~.......MtH....H",
  "%.i..D....i.M..~HHHH~..M.i....D....H",
  "%a...%.........~HHHH~.........H....H",
  "%.M..%...M.....~~~~~~.....M...H.g..H",
  "%...+%..o............b.......tH....H",
  "%....Dt........T....T.........D...hH",
  "%....%HHHHHH............HHHHHHH....H",
  "%%S%%%######............######HHHHHH",
  "#...########............############",
  "#*PA########t..........t############",
  "############.......b....############",
  "############............############",
  "###############.......##############",
  "##############..a.2..###############",
  "##############...p....##############",
  "##############t......t##############",
  "####################################",
  "####################################"
 ],
 "heights": [
  "000000000000000000000000000000000000",
  "00000066622222222aa22222222666000000",
  "000000666222222222222222222666000000",
  "000000666222222222222222222666000000",
  "000000666222222222222222222666000000",
  "000000666422222222222222224666000000",
  "000000666222222222222222222666000000",
  "000000666222202222222202222666000000",
  "000000666222202222222202222666000000",
  "000000666222202222222202222666000000",
  "000000666222222222222222222666000000",
  "000000000000000000000000000000000000",
  "000000000000000002200000000000000000",
  "00000000000000000aa00000000000000000",
  "000000000000000002200000000000000000",
  "00000000000000000aa00000000000000000",
  "066660088888800002200000000000011110",
  "06666008888888000aa00000000000011110",
  "066660222222222222222222222222011110",
  "011160222222222222222222222222011110",
  "011150222222222222222222222222002200",
  "011140222222222000000222222222002200",
  "011130222222222000000222222222002200",
  "011120222222222000000222222222011110",
  "011110222222222000000222222222011110",
  "011110222222222000000222222222011110",
  "011110222222222000000222222222011110",
  "011110222222222222222222222222011110",
  "011110222222222222222222222222011110",
  "011110000000332222222233000000011110",
  "000000000000442222222244000000000000",
  "011100000000552222222255000000000000",
  "011100000000666666666666000000000000",
  "000000000000666666666666000000000000",
  "000000000000666666666666000000000000",
  "000000000000006666666600000000000000",
  "000000000000006666666600000000000000",
  "000000000000006666666600000000000000",
  "000000000000006666666600000000000000",
  "000000000000000000000000000000000000",
  "000000000000000000000000000000000000"
 ],
 "ceilings": [
  "....................................",
  "......qqqqqqqqqqqqqqqqqqqqqqqq......",
  "......qqqqqqqqqqqqqqqqqqqqqqqq......",
  "......qqqqqqqqqqqqqqqqqqqqqqqq......",
  "......qqqqqqqqqqqqqqqqqqqqqqqq......",
  "......qqqqqqqqqqqqqqqqqqqqqqqq......",
  "......qqqqqqqqqqqqqqqqqqqqqqqq......",
  "......qqqqqqqqqqqqqqqqqqqqqqqq......",
  "......qqqqqqqqqqqqqqqqqqqqqqqq......",
  "......qqqqqqqqqqqqqqqqqqqqqqqq......",
  "......qqqqqqqqqqqqqqqqqqqqqqqq......",
  "....................................",
  ".................kk.................",
  ".................kk.................",
  ".................kk.................",
  ".................kk.................",
  ".kkkk..mmmmmm....kk............kkkk.",
  ".kkkk..mmmmmm....kk............kkkk.",
  ".kkkk.mmmmmmmmmmmmmmmmmmmmmmmm.kkkk.",
  ".kkkk.mmmmmmmmmmmmmmmmmmmmmmmm.kkkk.",
  ".kkkk.mmmmmmmmmmmmmmmmmmmmmmmm.kkkk.",
  ".kkkk.mmmmmmmmmmmmmmmmmmmmmmmm.kkkk.",
  ".kkkk.mmmmmmmmmmmmmmmmmmmmmmmm.kkkk.",
  ".kkkk.mmmmmmmmmmmmmmmmmmmmmmmm.kkkk.",
  ".kkkk.mmmmmmmmmmmmmmmmmmmmmmmm.kkkk.",
  ".kkkk.mmmmmmmmmmmmmmmmmmmmmmmm.kkkk.",
  ".kkkk.mmmmmmmmmmmmmmmmmmmmmmmm.kkkk.",
  ".kkkk.mmmmmmmmmmmmmmmmmmmmmmmm.kkkk.",
  ".kkkk.mmmmmmmmmmmmmmmmmmmmmmmm.kkkk.",
  ".kkkk.......mmmmmmmmmmmm.......kkkk.",
  "............mmmmmmmmmmmm............",
  ".kkk........mmmmmmmmmmmm............",
  ".kkk........mmmmmmmmmmmm............",
  "............mmmmmmmmmmmm............",
  "............mmmmmmmmmmmm............",
  "..............eeeeeeee..............",
  "..............eeeeeeee..............",
  "..............eeeeeeee..............",
  "..............eeeeeeee..............",
  "....................................",
  "...................................."
 ],
 "levers": [
  [
   2,
   15
  ],
  [
   33,
   15
  ],
  [
   9,
   15
  ]
 ],
 "leverGoal": "PULL THE SEAL LEVERS",
 "events": [
  {
   "when": {
    "start": true
   },
   "do": [
    {
     "light": "relit",
     "on": false
    },
    {
     "light": "relitW",
     "on": false
    },
    {
     "light": "relitE",
     "on": false
    },
    {
     "light": "relitHall",
     "on": false
    }
   ]
  },
  {
   "when": {
    "use": [
     2,
     15
    ]
   },
   "do": [
    {
     "notice": "THE WEST SEAL IS DOWN"
    },
    {
     "shake": 2
    },
    {
     "lower": [
      17,
      13,
      18,
      13
     ],
     "to": 0.5,
     "speed": 0.5
    },
    {
     "say": "THE WEST SEAL IS DOWN. HEAR THAT BELL? THE ENGINE HEARD IT TOO. HOLLOWS, DOWN BELOW!"
    },
    {
     "after": 2.5,
     "do": [
      {
       "wave": "answer1",
       "spawn": [
        {
         "kind": "imp",
         "x": 2,
         "z": 27
        },
        {
         "kind": "imp",
         "x": 1,
         "z": 28
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "when": {
    "use": [
     33,
     15
    ]
   },
   "do": [
    {
     "notice": "THE EAST SEAL IS DOWN"
    },
    {
     "shake": 2
    },
    {
     "lower": [
      17,
      15,
      18,
      15
     ],
     "to": 0.5,
     "speed": 0.5
    },
    {
     "say": "THE EAST SEAL IS DOWN. SOMETHING'S COMING OVER THE BRIDGE!"
    },
    {
     "after": 2.5,
     "do": [
      {
       "wave": "answer2",
       "spawn": [
        {
         "kind": "gnasher",
         "x": 33,
         "z": 27
        },
        {
         "kind": "imp",
         "x": 31,
         "z": 28
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "when": {
    "use": [
     9,
     15
    ]
   },
   "do": [
    {
     "notice": "THE GALLERY SEAL IS DOWN"
    },
    {
     "shake": 2
    },
    {
     "lower": [
      17,
      17,
      18,
      17
     ],
     "to": 0.5,
     "speed": 0.5
    },
    {
     "say": "THE GALLERY SEAL IS DOWN. HOLLOWS IN THE HALL! YOU'VE GOT THE HIGH GROUND, USE IT."
    },
    {
     "after": 2.5,
     "do": [
      {
       "wave": "answer3",
       "spawn": [
        {
         "kind": "imp",
         "x": 11,
         "z": 25
        },
        {
         "kind": "imp",
         "x": 24,
         "z": 25
        },
        {
         "kind": "gnasher",
         "x": 17,
         "z": 28
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "when": {
    "enter": [
     9,
     2,
     26,
     9
    ]
   },
   "do": [
    {
     "seal": [
      "17,11",
      "18,11"
     ]
    },
    {
     "notice": "THE RESET WARDEN!"
    },
    {
     "shake": 3
    },
    {
     "say": "THAT'S THE WARDEN. IT WAS A KNIGHT ONCE, SWORN TO A FIRE DRAKE, UNTIL THE OVERSEERS HOLLOWED IT OUT. STAY MOVING, USE THE PILLARS, RING IT WITH THE BELL BLASTER."
    },
    {
     "after": 1.5,
     "do": [
      {
       "wave": "warden",
       "spawn": [
        {
         "kind": "knight",
         "x": 17,
         "z": 6
        }
       ]
      },
      {
       "wave": "escort",
       "spawn": [
        {
         "kind": "imp",
         "x": 7,
         "z": 3
        },
        {
         "kind": "imp",
         "x": 28,
         "z": 3
        }
       ]
      }
     ]
    },
    {
     "after": 10,
     "do": [
      {
       "say": "IT'S CALLING HOLLOWS OUT OF THE WALLS!"
      },
      {
       "shake": 2
      },
      {
       "wave": "adds1",
       "spawn": [
        {
         "kind": "gnasher",
         "x": 9,
         "z": 9
        },
        {
         "kind": "gnasher",
         "x": 26,
         "z": 9
        },
        {
         "kind": "imp",
         "x": 12,
         "z": 2
        }
       ]
      }
     ]
    },
    {
     "after": 22,
     "do": [
      {
       "say": "HERE COMES EVERYTHING IT'S GOT. DON'T STOP MOVING!"
      },
      {
       "shake": 3
      },
      {
       "wave": "adds2",
       "spawn": [
        {
         "kind": "imp",
         "x": 7,
         "z": 9
        },
        {
         "kind": "imp",
         "x": 28,
         "z": 9
        },
        {
         "kind": "imp",
         "x": 23,
         "z": 2
        },
        {
         "kind": "gnasher",
         "x": 12,
         "z": 9
        },
        {
         "kind": "gnasher",
         "x": 23,
         "z": 9
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "when": {
    "cleared": "warden"
   },
   "do": [
    {
     "notice": "THE ENGINE IS SILENT"
    },
    {
     "shake": 4
    },
    {
     "light": "engine",
     "on": false
    },
    {
     "light": "core",
     "on": false
    },
    {
     "light": "relit",
     "on": true
    },
    {
     "light": "relitW",
     "on": true
    },
    {
     "light": "relitE",
     "on": true
    },
    {
     "light": "relitHall",
     "on": true
    },
    {
     "lava": [
      13,
      7,
      22,
      9
     ],
     "on": false
    },
    {
     "lava": [
      15,
      21,
      20,
      26
     ],
     "on": false
    },
    {
     "open": [
      "17,11",
      "18,11"
     ]
    },
    {
     "say": "YOU DID IT! THE ENGINE'S SILENT AND THE CITY'S LIGHTS ARE COMING BACK. THE WAYSTONE'S BEHIND IT. COME FIND ME AFTER."
    },
    {
     "lower": [
      17,
      1,
      18,
      1
     ],
     "to": 0.5,
     "speed": 1.0
    }
   ]
  }
 ],
 "triggers": [
  {
   "box": [
    14,
    35,
    21,
    38
   ],
   "say": "THIS STREET USED TO BE THE TOP OF THE CITY. THE OVERSEERS' ENGINE IS BURYING IT. THE BELL BLASTER'S RIGHT THERE, GRAB IT."
  },
  {
   "box": [
    12,
    32,
    23,
    34
   ],
   "say": "THERE IT IS: THE RESET ENGINE. THREE SEALS BLOCK THE WAY IN. EACH ONE HAS A LEVER: WEST, EAST, AND UP ON THAT GALLERY."
  },
  {
   "box": [
    1,
    19,
    4,
    29
   ],
   "say": "THE BELL WORKS. THE LEVER'S UP THE TOWER. THE STAIRS START AT THE BOTTOM."
  },
  {
   "box": [
    31,
    23,
    34,
    29
   ],
   "say": "CAREFUL, THAT CHANNEL IS RED MERCURY. TAKE THE BRIDGE. THE HOUNDS WON'T WAIT."
  },
  {
   "box": [
    14,
    12,
    21,
    17
   ],
   "say": "ALL THREE SEALS ARE DOWN. THE WARDEN'S BEHIND THOSE DOORS. HEALTH AND AMMO FIRST?"
  }
 ],
 "lights": [
  {
   "id": "core",
   "x": 17.5,
   "z": 23.5,
   "y": 3.5,
   "color": 16722480,
   "intensity": 5,
   "dist": 16
  },
  {
   "id": "engine",
   "x": 17.5,
   "z": 6.5,
   "y": 3.5,
   "color": 16722480,
   "intensity": 4.5,
   "dist": 16
  },
  {
   "id": "relit",
   "x": 17.5,
   "z": 7.5,
   "y": 3,
   "color": 9433343,
   "intensity": 12,
   "dist": 22
  },
  {
   "id": "relitW",
   "x": 9.5,
   "z": 5.5,
   "y": 3,
   "color": 9433343,
   "intensity": 6,
   "dist": 12
  },
  {
   "id": "relitE",
   "x": 25.5,
   "z": 5.5,
   "y": 3,
   "color": 9433343,
   "intensity": 6,
   "dist": 12
  },
  {
   "id": "relitHall",
   "x": 17.5,
   "z": 23.5,
   "y": 5,
   "color": 9433343,
   "intensity": 9,
   "dist": 20
  },
  {
   "id": "bells",
   "x": 2.5,
   "z": 22,
   "y": 3.5,
   "color": 9429247,
   "intensity": 2.4,
   "dist": 11
  },
  {
   "id": "foundry",
   "x": 32.5,
   "z": 21,
   "y": 1.5,
   "color": 16722480,
   "intensity": 3,
   "dist": 10
  },
  {
   "id": "street",
   "x": 17.5,
   "z": 37,
   "y": 2.4,
   "color": 16760960,
   "intensity": 1.4,
   "dist": 8,
   "flicker": true
  }
 ],
 "darkZones": [
  [
   14,
   35,
   21,
   38
  ]
 ]
};
