// Generated by tools/build_e1m4.py. Edit that, not this.
export var E1M4 = {
 "name": "E1M4: RILEY'S TRIAL",
 "floor": "slab",
 "ceil": "ceilDark",
 "par": 300,
 "playerAngle": -1.5707963,
 "ceilHeight": 2.5,
 "map": [
  "####TTTTTTTTTTTTTTTTTTTTTTTTTTTT####",
  "####T....b................b....T####",
  "####T.t......................t.T####",
  "####T.A....M.....Y......M....+.T####",
  "####T..........................T####",
  "####T..........................T####",
  "####T..........................T####",
  "####T..........................T####",
  "####T..........................T####",
  "####T......M............M......T####",
  "####T.a......................a.T####",
  "####T.t......................t.T####",
  "####T....h.......a........h....T####",
  "####TTTTTTTT............TTTTTTTT####",
  "###########T...a....b...T###########",
  "###########T............T###HHHHHHHH",
  "#.....a####TTTTTT..TTTTTT###H....+.H",
  "#...i..#########MRRM########H..r...H",
  "#..u...#########M..M########H......H",
  "#......#########M..M########H~~~~~~H",
  "#.#..L.#########M..M########H~~~~~~H",
  "#.#....#%%%%%%%%MUUM%%%%%%%%H~~~~~~H",
  "#.#....#........t..t........H~~~~~~H",
  "#.#....#t.i................tH~~~~~~H",
  "#.#....D....................D......H",
  "#.#....#...M............M...H......H",
  "#.#.b..#....................H......H",
  "#.#....#....................H.a....=",
  "#.#....#t..................tH......H",
  "#......D.....M........M.....D......H",
  "#..i.h.#....h...............H....gbH",
  "#......#..................o.H......H",
  "###S####.o..................HHHHHHHH",
  "##...##%....................%#######",
  "##*PA##%%%%%%%........%%%%%%%#######",
  "#############%..a.b...%#############",
  "#############%...p....%#############",
  "#############%t......t%#############",
  "#############%%%%%%%%%%#############"
 ],
 "heights": [
  "000000000000000000000000000000000000",
  "000008884444444444444444444488800000",
  "000008884444444444444444444488800000",
  "000008884444444444444444444488800000",
  "000008884444444444444444444488800000",
  "000008884444444444444444444488800000",
  "000008887654444444444444456788800000",
  "000008884444444444444444444488800000",
  "000008884444444444444444444488800000",
  "000008884444444444444444444488800000",
  "000008884444554444444455444488800000",
  "000008884444664444444466444488800000",
  "000004444444774444444477444444400000",
  "000000000000888888888888000000000000",
  "000000000000888888888888000000000000",
  "000000000000888888888888000000000000",
  "0cccccc00000000008800000000004444440",
  "0cccccc00000000008800000000004444440",
  "0cccccc00000000007700000000004444440",
  "0cccccc00000000006600000000000000000",
  "0c444c400000000005500000000000000000",
  "0c4444400000000004400000000000000000",
  "0c4444404444444444444444444400000000",
  "0c4444404444444444444444444400000000",
  "0c4444404444444444444444444404444440",
  "0c4444404444444444444444444404444440",
  "0a4444404444444444444444444404444440",
  "084444404444444444444444444404444440",
  "064444404444444444444444444404444440",
  "044444404444444444444444444404444440",
  "044444404444444444444444444404444440",
  "044444404444444455554444444404444440",
  "000000004444444466664444444400000000",
  "004440004444444477774444444400000000",
  "004440000000008888888800000000000000",
  "000000000000008888888800000000000000",
  "000000000000008888888800000000000000",
  "000000000000008888888800000000000000",
  "000000000000000000000000000000000000"
 ],
 "ceilings": [
  "....................................",
  ".....qqqqqqqqqqqqqqqqqqqqqqqqqq.....",
  ".....qqqqqqqqqqqqqqqqqqqqqqqqqq.....",
  ".....qqqqqqqqqqqqqqqqqqqqqqqqqq.....",
  ".....qqqqqqqqqqqqqqqqqqqqqqqqqq.....",
  ".....qqqqqqqqqqqqqqqqqqqqqqqqqq.....",
  ".....qqqqqqqqqqqqqqqqqqqqqqqqqq.....",
  ".....qqqqqqqqqqqqqqqqqqqqqqqqqq.....",
  ".....qqqqqqqqqqqqqqqqqqqqqqqqqq.....",
  ".....qqqqqqqqqqqqqqqqqqqqqqqqqq.....",
  ".....qqqqqqqqqqqqqqqqqqqqqqqqqq.....",
  ".....qqqqqqqqqqqqqqqqqqqqqqqqqq.....",
  ".....qqqqqqqqqqqqqqqqqqqqqqqqqq.....",
  "............qqqqqqqqqqqq............",
  "............qqqqqqqqqqqq............",
  "............qqqqqqqqqqqq............",
  ".qqqqqq..........mm..........qqqqqq.",
  ".qqqqqq..........mm..........qqqqqq.",
  ".qqqqqq..........mm..........qqqqqq.",
  ".qqqqqq..........mm..........qqqqqq.",
  ".qqqqqq..........mm..........qqqqqq.",
  ".qqqqqq..........mm..........qqqqqq.",
  ".qqqqqq.qqqqqqqqqqqqqqqqqqqq.qqqqqq.",
  ".qqqqqq.qqqqqqqqqqqqqqqqqqqq.qqqqqq.",
  ".qqqqqq.qqqqqqqqqqqqqqqqqqqq.qqqqqq.",
  ".qqqqqq.qqqqqqqqqqqqqqqqqqqq.qqqqqq.",
  ".qqqqqq.qqqqqqqqqqqqqqqqqqqq.qqqqqq.",
  ".qqqqqq.qqqqqqqqqqqqqqqqqqqq.qqqqqq.",
  ".qqqqqq.qqqqqqqqqqqqqqqqqqqq.qqqqqq.",
  ".qqqqqq.qqqqqqqqqqqqqqqqqqqq.qqqqqq.",
  ".qqqqqq.qqqqqqqqqqqqqqqqqqqq.qqqqqq.",
  ".qqqqqq.qqqqqqqqqqqqqqqqqqqq.qqqqqq.",
  "........qqqqqqqqqqqqqqqqqqqq........",
  "..qqq...qqqqqqqqqqqqqqqqqqqq........",
  "..qqq.........qqqqqqqq..............",
  "..............qqqqqqqq..............",
  "..............qqqqqqqq..............",
  "..............qqqqqqqq..............",
  "...................................."
 ],
 "intro": [
  "THE TOP OF THE WORLD. A SEALED WAYSTONE.",
  "RILEY REMEMBERS HOW YOU FOUGHT."
 ],
 "events": [
  {
   "when": {
    "use": [
     35,
     27
    ]
   },
   "do": [
    {
     "notice": "THE MERCURY IS DRAINING!"
    },
    {
     "shake": 2
    },
    {
     "lava": [
      29,
      19,
      34,
      23
     ],
     "on": false
    },
    {
     "raise": [
      29,
      19,
      34,
      23
     ],
     "to": 1.0,
     "speed": 0.35
    },
    {
     "say": "THERE IT GOES. THE KEYSTONE'S ON THE ISLAND. WATCH OUT, THE HOLLOWS HEARD THAT."
    },
    {
     "after": 3,
     "do": [
      {
       "wave": "island",
       "spawn": [
        {
         "kind": "imp",
         "x": 32,
         "z": 16
        },
        {
         "kind": "imp",
         "x": 30,
         "z": 16
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "when": {
    "enter": [
     5,
     1,
     30,
     12
    ]
   },
   "do": [
    {
     "seal": [
      "17,17",
      "18,17"
     ]
    },
    {
     "notice": "RILEY'S TRIAL"
    },
    {
     "shake": 1
    },
    {
     "after": 42,
     "do": [
      {
       "notice": "THE FLOOR IS MOVING!"
      },
      {
       "shake": 2
      }
     ]
    },
    {
     "after": 44,
     "do": [
      {
       "raise": [
        14,
        4,
        14,
        4
       ],
       "to": 2.0,
       "speed": 0.8
      },
      {
       "raise": [
        21,
        4,
        21,
        4
       ],
       "to": 2.0,
       "speed": 0.8
      },
      {
       "raise": [
        14,
        8,
        14,
        8
       ],
       "to": 2.0,
       "speed": 0.8
      },
      {
       "raise": [
        21,
        8,
        21,
        8
       ],
       "to": 2.0,
       "speed": 0.8
      }
     ]
    }
   ]
  }
 ],
 "triggers": [
  {
   "box": [
    14,
    34,
    21,
    37
   ],
   "say": "YOU MADE IT TO THE TOP OF THE WORLD. MY TRIAL IS PAST THAT GATE. TWO KEYSTONES OPEN IT: ONE IN THE TRIAL OF ASH, WEST, ONE IN THE TRIAL OF MERCURY, EAST."
  },
  {
   "box": [
    1,
    20,
    6,
    31
   ],
   "say": "THE TRIAL OF ASH. EVERYTHING FROM THE GATES: JUMP UP THE STEPS, OR RIDE THE LIFT."
  },
  {
   "box": [
    29,
    24,
    34,
    31
   ],
   "say": "THE TRIAL OF MERCURY. YOU'VE DRAINED ONE OF THESE BEFORE. FIND THE SWITCH."
  },
  {
   "box": [
    17,
    18,
    18,
    20
   ],
   "say": "BOTH KEYSTONES. OKAY. COME UP AND SHOW ME WHAT YOU'VE LEARNED."
  }
 ],
 "lights": [
  {
   "id": "beam",
   "x": 17.5,
   "z": 6.5,
   "y": 6,
   "color": 9433343,
   "intensity": 6,
   "dist": 26
  },
  {
   "id": "arenaW",
   "x": 7.5,
   "z": 6.5,
   "y": 3,
   "color": 9429247,
   "intensity": 2.5,
   "dist": 12
  },
  {
   "id": "arenaE",
   "x": 27.5,
   "z": 6.5,
   "y": 3,
   "color": 9429247,
   "intensity": 2.5,
   "dist": 12
  },
  {
   "id": "ash",
   "x": 3.5,
   "z": 24,
   "y": 3,
   "color": 16752736,
   "intensity": 2.4,
   "dist": 12
  },
  {
   "id": "mercury",
   "x": 31.5,
   "z": 21,
   "y": 1.5,
   "color": 16722480,
   "intensity": 3,
   "dist": 10
  },
  {
   "id": "court",
   "x": 17.5,
   "z": 27,
   "y": 5,
   "color": 16769200,
   "intensity": 2,
   "dist": 16
  }
 ]
};
